# Generated by Django 4.1.4 on 2023-01-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
