# Generated by Django 4.1.4 on 2023-01-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyapp', '0003_rename_age_studentdb_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='catdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(blank=True, max_length=30, null=True)),
                ('catdis', models.CharField(blank=True, max_length=30, null=True)),
                ('catimg', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
